# Generated by Django 4.2.15 on 2025-02-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_ordem_cor_ordem_data_carga_ordem_setor_conjunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=20)),
                ('status', models.CharField(default='livre', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=255)),
                ('qtd_planejada', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
                ('qtd_boa', models.FloatField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_pintura', to='core.ordem')),
            ],
        ),
        migrations.CreateModel(
            name='CambaoPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pendurada', models.FloatField(default=0)),
                ('data_pendura', models.DateTimeField(auto_now_add=True)),
                ('cambao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_no_cambao', to='apontamento_pintura.cambao')),
                ('peca_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambao_peca_ordem_pintura', to='apontamento_pintura.pecasordem')),
            ],
        ),
    ]
