# Generated by Django 4.2.15 on 2025-02-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0002_pecasordem_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cambao',
            name='data_fim',
        ),
        migrations.AddField(
            model_name='cambaopecas',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cambaopecas',
            name='status',
            field=models.CharField(default='pendurada', max_length=20),
        ),
    ]
