# Generated by Django 4.2.15 on 2025-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0003_remove_cambao_data_criacao_remove_cambao_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambaopecas',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
