# Generated by Django 4.2.15 on 2025-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0004_cambaopecas_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambaopecas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cambao',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
