# Generated by Django 4.2.15 on 2025-02-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_alter_conjuntos_codigo'),
        ('apontamento_pintura', '0005_remove_cambaopecas_tipo_cambao_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecasordem',
            old_name='operador',
            new_name='operador_inicio',
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='operador_fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_fim_pintura', to='cadastro.operador'),
        ),
    ]
