# Generated by Django 4.2.15 on 2025-02-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_alter_conjuntos_codigo'),
        ('apontamento_pintura', '0006_rename_operador_pecasordem_operador_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasordem',
            name='operador_fim',
        ),
        migrations.AddField(
            model_name='cambaopecas',
            name='operador_fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_fim_pintura', to='cadastro.operador'),
        ),
    ]
