# Generated by Django 4.2.15 on 2025-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0008_remove_cambaopecas_operador_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambao',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
