# Generated by Django 5.0.6 on 2025-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0008_remove_cambaopecas_operador_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
