# Generated by Django 5.0.6 on 2025-02-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0009_retrabalho'),
        ('inspecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrabalho',
            name='reinspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.reinspecao'),
        ),
    ]
