# Generated by Django 5.0.6 on 2025-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0010_retrabalho_reinspecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrabalho',
            name='status',
            field=models.CharField(choices=[('a retrabalhar', 'A Retrabalhar'), ('em processo', 'Em processo'), ('finalizado', 'Finalizado')], max_length=20),
        ),
    ]
