# Generated by Django 5.0.6 on 2025-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0011_alter_retrabalho_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrabalho',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
