# Generated by Django 4.2.15 on 2025-03-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0009_cambao_nome'),
        ('apontamento_pintura', '0012_alter_retrabalho_data_inicio'),
    ]

    operations = [
    ]
