# Generated by Django 4.2.15 on 2025-05-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0014_merge_20250408_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambaopecas',
            name='peca_ordem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambao_peca_ordem_pintura', to='apontamento_pintura.pecasordem'),
        ),
    ]
