# Generated by Django 4.2.15 on 2025-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0015_alter_cambaopecas_peca_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
