# Generated by Django 4.2.16 on 2025-09-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0016_cambao_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polimerizacao', models.BooleanField(blank=True, null=True)),
                ('aderencia', models.BooleanField(blank=True, default=False, null=True)),
                ('espessura_camada_1', models.FloatField(blank=True, null=True)),
                ('espessura_camada_2', models.FloatField(blank=True, null=True)),
                ('espessura_camada_3', models.FloatField(blank=True, null=True)),
                ('tonalidade', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('peca_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teste_funcional_peca_ordem_pintura', to='apontamento_pintura.pecasordem')),
            ],
        ),
    ]
