# Generated by Django 4.2.16 on 2025-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0017_testefuncional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testefuncional',
            name='data_realizacao',
        ),
        migrations.AddField(
            model_name='testefuncional',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='testefuncional',
            name='data_inicial',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
