# Generated by Django 4.2.16 on 2025-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0018_remove_testefuncional_data_realizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testefuncional',
            name='aderencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testefuncional',
            name='tonalidade',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
