# Generated by Django 4.2.16 on 2025-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0019_alter_testefuncional_aderencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testefuncional',
            name='meta_espessura_camada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
