# Generated by Django 4.2.16 on 2025-09-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0020_testefuncional_meta_espessura_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='testefuncional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_verificacao_funcional/'),
        ),
    ]
