# Generated by Django 4.2.16 on 2025-09-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_rotaacesso_app'),
        ('apontamento_pintura', '0021_testefuncional_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='testefuncional',
            name='inspetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
