# Generated by Django 4.2.15 on 2026-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0023_programa_programacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='status',
        ),
        migrations.AddField(
            model_name='programa',
            name='status',
            field=models.CharField(default='programada', max_length=20),
        ),
    ]
