# Generated by Django 4.2.15 on 2026-01-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0024_remove_programacao_status_programa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='peca_ordem',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='programa',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
    ]
