# Generated by Django 4.2.15 on 2026-01-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0025_remove_programacao_peca_ordem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_programa', models.IntegerField()),
                ('prioridade', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_tinta', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('data_planejada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='programada', max_length=20)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_programacao', models.FloatField(default=0)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('peca_ordem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacao_peca_ordem_pintura', to='apontamento_pintura.pecasordem')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacao_pintura', to='apontamento_pintura.programa')),
            ],
        ),
    ]
