# Generated by Django 4.2.15 on 2026-01-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0026_programa_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambaoInterrupcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('cambao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrupcoes', to='apontamento_pintura.cambao')),
            ],
            options={
                'verbose_name': 'Interrupção de Cambão',
                'verbose_name_plural': 'Interrupções de Cambões',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
