# Generated by Django 4.2.15 on 2026-01-14 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0027_cambaointerrupcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambaopecas',
            name='identificador_lote',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
