# Generated by Django 4.2.15 on 2026-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_pintura', '0028_cambaopecas_identificador_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambaopecas',
            name='identificador_lote',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
