# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apontamento_pintura", "0029_alter_cambaopecas_identificador_lote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlePintura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField(blank=True, null=True)),
                ("fornecedor", models.CharField(blank=True, max_length=120)),
                ("cor", models.CharField(blank=True, max_length=80)),
                ("lote", models.CharField(blank=True, max_length=80)),
                ("quantidade_tinta", models.CharField(blank=True, max_length=80)),
                ("catalizador", models.CharField(blank=True, max_length=80)),
                ("diluente", models.CharField(blank=True, max_length=80)),
                ("viscosidade", models.CharField(blank=True, max_length=40)),
                ("pintor", models.CharField(blank=True, max_length=120)),
                ("pistola", models.CharField(blank=True, max_length=80)),
                ("qnt_demaos", models.CharField(blank=True, max_length=40)),
                ("pressao_ar_1", models.CharField(blank=True, max_length=40)),
                ("pressao_ar_2", models.CharField(blank=True, max_length=40)),
                ("pressao_ar_3", models.CharField(blank=True, max_length=40)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Controle de Pintura",
                "verbose_name_plural": "Controles de Pintura",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
