# Generated by Django 4.2.15 on 2024-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0007_delete_pecaprocesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('grupo_maquina', models.CharField(blank=True, choices=[('laser', 'Laser'), ('plasma', 'Plasma'), ('prensa', 'Prensa')], max_length=20, null=True)),
                ('maquina', models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma_1', 'Plasma 1'), ('plasma_2', 'Plasma 2'), ('prensa', 'Prensa')], max_length=20, null=True)),
                ('status_atual', models.CharField(choices=[('aguardando_iniciar', 'Aguardando iniciar'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('interrompida', 'Interrompida')], default='aguardando_iniciar', max_length=20)),
                ('status_prioridade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropriedadesOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_mp', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=100)),
                ('espessura', models.CharField(max_length=20)),
                ('quantidade', models.FloatField()),
                ('aproveitamento', models.CharField(max_length=10)),
                ('tipo_chapa', models.CharField(choices=[('aco_carbono', 'Aço carbono'), ('anti_derrapante', 'Anti derrapante'), ('alta_resistencia', 'Alta resistência')], max_length=20)),
                ('retalho', models.BooleanField(default=False)),
                ('ordem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propriedade', to='core.ordem')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_iniciar', 'Aguardando iniciar'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('interrompida', 'Interrompida')], max_length=20)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('motivo_interrupcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivointerrupcao')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='core.ordem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordem',
            constraint=models.UniqueConstraint(fields=('ordem', 'maquina'), name='unique_ordem_processo'),
        ),
    ]
