# Generated by Django 4.2.15 on 2024-12-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_mp_setor'),
        ('core', '0002_alter_ordem_grupo_maquina_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedadesordem',
            name='mp_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp', to='cadastro.mp'),
        ),
    ]
