# Generated by Django 4.2.15 on 2024-12-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propriedadesordem_mp_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedadesordem',
            name='descricao_mp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propriedadesordem',
            name='espessura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propriedadesordem',
            name='tamanho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propriedadesordem',
            name='tipo_chapa',
            field=models.CharField(blank=True, choices=[('aco_carbono', 'Aço carbono'), ('anti_derrapante', 'Anti derrapante'), ('alta_resistencia', 'Alta resistência')], max_length=20, null=True),
        ),
    ]
