# Generated by Django 4.2.15 on 2024-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_propriedadesordem_descricao_mp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedadesordem',
            name='aproveitamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
