# Generated by Django 4.2.15 on 2024-12-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_mp_setor'),
        ('core', '0005_alter_propriedadesordem_aproveitamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='operador_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador', to='cadastro.operador'),
        ),
    ]
