# Generated by Django 4.2.15 on 2024-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordem_operador_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='obs_operador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
