# Generated by Django 4.2.15 on 2024-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ordem_obs_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='maquina',
            field=models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma_1', 'Plasma 1'), ('plasma_2', 'Plasma 2'), ('prensa', 'Prensa'), ('furadeira', 'Furadeira'), ('centro_de_usinagem', 'Centro de usinagem'), ('serra_1', 'Serra 1'), ('serra_2', 'Serra 2'), ('torno', 'Torno'), ('chanfradeira', 'Chanfradeira')], max_length=20, null=True),
        ),
    ]
