# Generated by Django 4.2.15 on 2024-12-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='data_programacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
