# Generated by Django 4.2.15 on 2024-12-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_operador_matricula'),
        ('core', '0009_ordem_data_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedadesordem',
            name='nova_mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nova_mp', to='cadastro.mp'),
        ),
    ]
