# Generated by Django 4.2.15 on 2024-12-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_propriedadesordem_nova_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='grupo_maquina',
            field=models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma', 'Plasma'), ('prensa', 'Prensa'), ('usinagem', 'Usinagem'), ('serra', 'Serra')], max_length=20, null=True),
        ),
    ]
