# Generated by Django 4.2.15 on 2025-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ordemprocesso_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='status_atual',
            field=models.CharField(choices=[('aguardando_iniciar', 'Aguardando iniciar'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('interrompida', 'Interrompida'), ('agua_prox_proc', 'Aguardando prox processo')], default='aguardando_iniciar', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemprocesso',
            name='status',
            field=models.CharField(choices=[('aguardando_iniciar', 'Aguardando iniciar'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('interrompida', 'Interrompida'), ('agua_prox_proc', 'Aguardando prox processo')], max_length=20),
        ),
    ]
