# Generated by Django 4.2.15 on 2025-01-10 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
