# Generated by Django 4.2.15 on 2025-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ordem_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
