# Generated by Django 4.2.15 on 2025-01-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_motivoexclusao'),
        ('core', '0019_alter_ordem_grupo_maquina_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='duplicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordem',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordem',
            name='motivo_exclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivointerrupcao'),
        ),
        migrations.AddField(
            model_name='ordem',
            name='ordem_duplicada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='ordem_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_filhas', to='core.ordem', verbose_name='Ordem Pai'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
