# Generated by Django 4.2.15 on 2025-01-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_maquinaparada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaquinaParada',
        ),
    ]
