# Generated by Django 4.2.15 on 2025-01-24 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_motivomaquinaparada'),
        ('core', '0022_delete_maquinaparada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma_1', 'Plasma 1'), ('plasma_2', 'Plasma 2'), ('prensa', 'Prensa'), ('furadeira_1', 'Furadeira 1'), ('furadeira_2', 'Furadeira 2'), ('furadeira_3', 'Furadeira 3'), ('furadeira_4', 'Furadeira 4'), ('furadeira_5', 'Furadeira 5'), ('furadeira_6', 'Furadeira 6'), ('furadeira_7', 'Furadeira 7'), ('centro_de_usinagem', 'Centro de usinagem'), ('serra_1', 'Serra 1'), ('serra_2', 'Serra 2'), ('serra_3', 'Serra 3'), ('torno_1', 'Torno 1'), ('torno_2', 'Torno 2'), ('chanfradeira', 'Chanfradeira'), ('maq_solda', 'Máquina de solda'), ('furar', 'Furar'), ('chanfrar', 'Chanfrar'), ('tornear', ' Tornear'), ('viradeira_1', 'Viradeira 1'), ('viradeira_2', 'Viradeira 2'), ('viradeira_3', 'Viradeira 3'), ('viradeira_4', 'Viradeira 4'), ('viradeira_5', 'Viradeira 5'), ('prensa', 'Prensa')], max_length=30)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivointerrupcao')),
            ],
        ),
    ]
