# Generated by Django 4.2.15 on 2025-01-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_motivomaquinaparada'),
        ('core', '0023_maquinaparada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivomaquinaparada'),
        ),
    ]
