# Generated by Django 4.2.15 on 2025-01-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_motivomaquinaparada'),
        ('core', '0025_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='motivo_exclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivoexclusao'),
        ),
    ]
