# Generated by Django 4.2.15 on 2025-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ordem_motivo_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedadesordem',
            name='aproveitamento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
