# Generated by Django 4.2.15 on 2025-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_propriedadesordem_aproveitamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, unique=True)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('bug', 'Bug'), ('funcionalidade', 'Funcionalidade'), ('implementacao', 'Implementação')], max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
