# Generated by Django 4.2.15 on 2025-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_versao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='data_lancamento',
            field=models.DateField(),
        ),
    ]
