# Generated by Django 4.2.15 on 2025-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_versao_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='maquina',
            field=models.CharField(choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma_1', 'Plasma 1'), ('plasma_2', 'Plasma 2'), ('prensa', 'Prensa'), ('serra_1', 'Serra 1'), ('serra_2', 'Serra 2'), ('serra_3', 'Serra 3'), ('furadeira_1', 'Furadeira 1'), ('furadeira_2', 'Furadeira 2'), ('furadeira_3', 'Furadeira 3'), ('furadeira_4', 'Furadeira 4'), ('furadeira_5', 'Furadeira 5'), ('furadeira_6', 'Furadeira 6'), ('furadeira_7', 'Furadeira 7'), ('centro_de_usinagem', 'Centro de usinagem'), ('torno_1', 'Torno 1'), ('torno_2', 'Torno 2'), ('chanfradeira', 'Chanfradeira'), ('furar', 'Furar'), ('chanfrar', 'Chanfrar'), ('tornear', ' Tornear'), ('viradeira_1', 'Viradeira 1'), ('viradeira_2', 'Viradeira 2'), ('viradeira_3', 'Viradeira 3'), ('viradeira_4', 'Viradeira 4'), ('viradeira_5', 'Viradeira 5'), ('prensa', 'Prensa'), ('maq_solda', 'Máquina de solda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='maquina',
            field=models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma_1', 'Plasma 1'), ('plasma_2', 'Plasma 2'), ('prensa', 'Prensa'), ('serra_1', 'Serra 1'), ('serra_2', 'Serra 2'), ('serra_3', 'Serra 3'), ('furadeira_1', 'Furadeira 1'), ('furadeira_2', 'Furadeira 2'), ('furadeira_3', 'Furadeira 3'), ('furadeira_4', 'Furadeira 4'), ('furadeira_5', 'Furadeira 5'), ('furadeira_6', 'Furadeira 6'), ('furadeira_7', 'Furadeira 7'), ('centro_de_usinagem', 'Centro de usinagem'), ('torno_1', 'Torno 1'), ('torno_2', 'Torno 2'), ('chanfradeira', 'Chanfradeira'), ('furar', 'Furar'), ('chanfrar', 'Chanfrar'), ('tornear', ' Tornear'), ('viradeira_1', 'Viradeira 1'), ('viradeira_2', 'Viradeira 2'), ('viradeira_3', 'Viradeira 3'), ('viradeira_4', 'Viradeira 4'), ('viradeira_5', 'Viradeira 5'), ('prensa', 'Prensa'), ('maq_solda', 'Máquina de solda')], max_length=20, null=True),
        ),
    ]
