# Generated by Django 4.2.15 on 2025-02-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_motivomaquinaparada'),
        ('core', '0030_alter_maquinaparada_maquina_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquina_ordem', to='cadastro.maquina'),
        ),
    ]
