# Generated by Django 4.2.15 on 2025-02-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_maquina_tipo'),
        ('core', '0031_alter_ordem_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquina_maquina_parada', to='cadastro.maquina'),
        ),
    ]
