# Generated by Django 4.2.15 on 2025-02-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_maquina_tipo'),
        ('core', '0032_alter_maquinaparada_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemprocesso',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_maquina', to='cadastro.maquina'),
        ),
    ]
