# Generated by Django 4.2.15 on 2025-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_ordemprocesso_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='data_carga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='setor_conjunto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='tipo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='grupo_maquina',
            field=models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('plasma', 'Plasma'), ('prensa', 'Prensa'), ('usinagem', 'Usinagem'), ('serra', 'Serra'), ('prod_esp', 'Prod. Especiais'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20, null=True),
        ),
    ]
