# Generated by Django 4.2.15 on 2025-02-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_ordem_cor_ordem_data_carga_ordem_setor_conjunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='setor_conjunto',
        ),
    ]
