# Generated by Django 5.0.6 on 2025-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_ordem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_acesso',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('pcp', 'PCP'), ('inspetor', 'Inspetor')], max_length=20),
        ),
    ]
