# Generated by Django 5.0.6 on 2025-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_profile_tipo_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_rota', models.CharField(choices=[('api', 'Api'), ('template', 'Template')], max_length=10)),
                ('app', models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('usinagem', 'Usinagem'), ('cargas', 'Cargas'), ('inspecao', 'Inspeção')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='setores_permitidos',
        ),
        migrations.AddField(
            model_name='profile',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='core.rotaacesso'),
        ),
    ]
