# Generated by Django 4.2.15 on 2025-02-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_remove_pecas_unique_codigo_pecas_conjunto_and_more'),
        ('core', '0037_solicitacaopeca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaopeca',
            name='setor_solicitante',
        ),
        migrations.AddField(
            model_name='solicitacaopeca',
            name='localizacao_solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localizacao_solicitacao_peca', to='cadastro.maquina'),
            preserve_default=False,
        ),
    ]
