# Generated by Django 4.2.15 on 2025-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_solicitacaopeca_setor_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissoes',
            field=models.JSONField(default=dict),
        ),
    ]
