# Generated by Django 4.2.15 on 2025-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_profile_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='setores_permitidos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permissoes',
        ),
        migrations.AddField(
            model_name='profile',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='core.rotaacesso'),
        ),
    ]
