# Generated by Django 4.2.15 on 2025-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rotaacesso_remove_profile_setores_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaacesso',
            name='app',
            field=models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('usinagem', 'Usinagem')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotaacesso',
            name='tipo_rota',
            field=models.CharField(choices=[('api', 'Api'), ('template', 'Template')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
