# Generated by Django 4.2.15 on 2025-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_rotaacesso_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='sequenciada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
