# Generated by Django 4.2.15 on 2025-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_ordem_sequenciada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='motivo_retirar_sequenciada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
