# Generated by Django 4.2.15 on 2025-03-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_alter_maquina_nome'),
        ('core', '0044_ordem_motivo_retirar_sequenciada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='motivo_retirar_sequenciada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivo_retirar_sequenciada', to='cadastro.motivoexclusao'),
        ),
    ]
