# Generated by Django 4.2.15 on 2025-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_profile_tipo_acesso'),
        ('core', '0045_alter_ordem_motivo_retirar_sequenciada'),
    ]

    operations = [
    ]
