# Generated by Django 4.2.15 on 2025-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20250408_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedadesordem',
            name='tipo_chapa',
            field=models.CharField(blank=True, choices=[('aco_carbono', 'Aço carbono'), ('anti_derrapante', 'Anti derrapante'), ('inox', 'Inox'), ('alta_resistencia', 'Alta resistência')], max_length=20, null=True),
        ),
    ]
