# Generated by Django 4.2.15 on 2025-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_propriedadesordem_tipo_chapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='ordem_prioridade',
            field=models.IntegerField(null=True),
        ),
    ]
