# Generated by Django 4.2.15 on 2025-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_ordem_ordem_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotaacesso',
            name='app',
            field=models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('sucata', 'Sucata'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('usinagem', 'Usinagem'), ('cargas', 'Cargas'), ('inspecao', 'Inspeção')], max_length=50),
        ),
    ]
