# Generated by Django 5.0.6 on 2025-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_rotaacesso_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='grupo_maquina',
            field=models.CharField(blank=True, choices=[('laser_1', 'Laser 1'), ('laser_2', 'Laser 2 (JFY)'), ('laser_3', 'Laser 3 (Trumpf)'), ('plasma', 'Plasma'), ('prensa', 'Prensa'), ('usinagem', 'Usinagem'), ('serra', 'Serra'), ('prod_esp', 'Prod. Especiais'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20, null=True),
        ),
    ]
