# Generated by Django 5.2.4 on 2025-07-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_ordem_grupo_maquina'),
        ('core', '0051_ordem_tempo_estimado_alter_ordem_grupo_maquina'),
    ]

    operations = [
    ]
