# Generated by Django 5.2.4 on 2025-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20250730_0851'),
        ('core', '0052_merge_20250730_1027'),
    ]

    operations = [
    ]
