# Generated by Django 4.2.15 on 2025-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20250812_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemprocesso',
            name='comentario_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
