# Generated by Django 4.2.15 on 2025-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_ordemprocesso_comentario_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotaacesso',
            name='app',
            field=models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('sucata', 'Sucata'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('solda', 'Solda'), ('expedicao', 'Expedição'), ('usinagem', 'Usinagem'), ('cargas', 'Cargas'), ('inspecao', 'Inspeção')], max_length=50),
        ),
    ]
