# Generated by Django 4.2.16 on 2025-09-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_rotaacesso_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_acesso',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('pcp', 'PCP'), ('inspetor', 'Inspetor'), ('almoxarifado', 'Almoxarifado'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rotaacesso',
            name='app',
            field=models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('sucata', 'Sucata'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('solda', 'Solda'), ('expedicao', 'Expedição'), ('usinagem', 'Usinagem'), ('cargas', 'Cargas'), ('inspecao', 'Inspeção'), ('almoxarifado', 'Almoxarifado')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('alerta', 'Alerta'), ('aviso', 'Aviso'), ('erro', 'Erro')], default='info', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.profile')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rotaacesso')),
            ],
        ),
    ]
