# Generated by Django 4.2.16 on 2025-09-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_profile_tipo_acesso_alter_rotaacesso_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='rota',
        ),
    ]
