# Generated by Django 4.2.16 on 2025-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_notificacao_rota'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroNotificacao',
            fields=[
                ('chave', models.CharField(help_text="Chave única para identificar a notificação periódica, ex: 'solicitacao_diaria_almoxarifado'", max_length=150, primary_key=True, serialize=False, unique=True)),
                ('ultimo_envio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificacao',
            name='rota_acesso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
