# Generated by Django 4.2.16 on 2025-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_registronotificacao_notificacao_rota_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
