# Generated by Django 4.2.16 on 2025-09-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_registronotificacao_notificacao_rota_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasFaltantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=255, verbose_name='Nome da Peça Faltante')),
                ('quantidade', models.FloatField(verbose_name='Quantidade Faltante')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_faltantes', to='core.ordem')),
            ],
            options={
                'verbose_name': 'Peça Faltante',
                'verbose_name_plural': 'Peças Faltantes',
            },
        ),
    ]
