# Generated by Django 4.2.16 on 2025-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pecasfaltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasfaltantes',
            name='numero_interrupcao',
            field=models.IntegerField(default=1, verbose_name='Número da Interrupção'),
        ),
    ]
