# Generated by Django 5.2.4 on 2025-09-24 18:03

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_ordem_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qrcodes/'),
        ),
    ]
