# Generated by Django 4.2.16 on 2025-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_ordem_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='caminho_relativo_qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
