# Generated by Django 4.2.15 on 2025-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_ordem_caminho_relativo_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedadesordem',
            name='apontamento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propriedadesordem',
            name='obs_apontamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
