# Generated by Django 4.2.15 on 2025-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_pecasfaltantes_numero_interrupcao'),
        ('core', '0061_ordem_caminho_relativo_qr_code'),
    ]

    operations = [
    ]
