# Generated by Django 4.2.15 on 2026-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_merge_20251107_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSaldoInnovaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupamento', models.CharField(max_length=100)),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.TextField()),
                ('saldo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('custo_total', models.DecimalField(decimal_places=8, max_digits=18)),
                ('custo_medio', models.DecimalField(decimal_places=9, max_digits=18)),
                ('data_ultimo_saldo', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'saldo_erp',
                'indexes': [models.Index(fields=['codigo', 'agrupamento'], name='saldo_erp_codigo_828f59_idx'), models.Index(fields=['agrupamento', 'data_ultimo_saldo'], name='saldo_erp_agrupam_27f2b5_idx')],
            },
        ),
    ]
