# Generated by Django 4.2.15 on 2025-11-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0062_propriedadesordem_apontamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedadesordem',
            name='transferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propriedadesordem',
            name='transferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedadesordem_transferidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
