# Generated by Django 4.2.15 on 2026-01-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_consultasaldoinnovaro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consultasaldoinnovaro',
            new_name='core_consul_codigo_f3813a_idx',
            old_name='saldo_erp_codigo_828f59_idx',
        ),
        migrations.RenameIndex(
            model_name='consultasaldoinnovaro',
            new_name='core_consul_agrupam_41b681_idx',
            old_name='saldo_erp_agrupam_27f2b5_idx',
        ),
        migrations.AlterModelTable(
            name='consultasaldoinnovaro',
            table=None,
        ),
    ]
