# Generated by Django 4.2.15 on 2026-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_rename_saldo_erp_codigo_828f59_idx_core_consul_codigo_f3813a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='agrupamento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='codigo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='custo_medio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='custo_total',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='data_ultimo_saldo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultasaldoinnovaro',
            name='saldo',
            field=models.TextField(),
        ),
    ]
