# Generated by Django 4.2.15 on 2026-01-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_consultasaldoinnovaro_agrupamento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultasaldoinnovaro',
            name='core_consul_codigo_f3813a_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultasaldoinnovaro',
            name='core_consul_agrupam_41b681_idx',
        ),
    ]
