# Generated by Django 4.2.16 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ordem_carga_liberada_relacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_acesso',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('pcp', 'PCP'), ('inspetor', 'Inspetor'), ('almoxarifado', 'Almoxarifado'), ('compras', 'Compras'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rotaacesso',
            name='app',
            field=models.CharField(choices=[('core', 'Core'), ('users', 'Users'), ('sucata', 'Sucata'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('montagem', 'Montagem'), ('pintura', 'Pintura'), ('prod_especiais', 'Prod Especiais'), ('corte', 'Corte'), ('solda', 'Solda'), ('expedicao', 'Expedição'), ('usinagem', 'Usinagem'), ('cargas', 'Cargas'), ('inspecao', 'Inspeção'), ('almoxarifado', 'Almoxarifado'), ('compras', 'Compras')], max_length=50),
        ),
    ]
