# Generated by Django 5.2.4 on 2025-09-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_almox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitacao', models.CharField(max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_cc', to='cadastro_almox.cc')),
                ('deposito_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_deposito_destino', to='cadastro_almox.depositodestino')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_item', to='cadastro_almox.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoNovaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cadastro_cc', to='cadastro_almox.cc')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('rpa', models.TextField(blank=True, null=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_cc', to='cadastro_almox.cc')),
                ('classe_requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_classe', to='cadastro_almox.classerequisicao')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_operador', to='cadastro_almox.operadoralmox')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_funcionario', to='cadastro_almox.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_itens', to='cadastro_almox.itenssolicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('rpa', models.TextField(blank=True, null=True)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_deposito_destino', to='cadastro_almox.depositodestino')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_operador', to='cadastro_almox.operadoralmox')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_funcionario', to='cadastro_almox.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_itens', to='cadastro_almox.itenstransferencia')),
            ],
        ),
    ]
