# Generated by Django 4.2.16 on 2025-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_almox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaorequisicao',
            name='chave_innovaro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaotransferencia',
            name='chave_innovaro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
