# Generated by Django 4.2.16 on 2026-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_almox', '0003_solicitacaorequisicao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaorequisicao',
            name='quantidade_entregue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaotransferencia',
            name='quantidade_entregue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
