# Generated by Django 4.2.15 on 2025-01-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0014_processo'),
        ('core', '0019_alter_ordem_grupo_maquina_alter_ordem_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_planejada', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
                ('qtd_boa', models.FloatField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_produzido_estamparia', to='cadastro.operador')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_estamparia', to='core.ordem')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_ordem_estamparia', to='cadastro.pecas')),
            ],
        ),
    ]
