# Generated by Django 5.0.6 on 2025-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAdicionaisInspecaoEstamparia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('inspecao_completa', models.BooleanField(default=False)),
                ('qtd_mortas', models.IntegerField(default=0)),
                ('motivo_mortas', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha', models.FileField(blank=True, null=True, upload_to='ficha_estamparia/')),
            ],
        ),
        migrations.CreateModel(
            name='MedidasInspecaoEstamparia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho_medida_a', models.CharField(blank=True, max_length=10, null=True)),
                ('medida_a', models.FloatField(blank=True, null=True)),
                ('cabecalho_medida_b', models.CharField(blank=True, max_length=10, null=True)),
                ('medida_b', models.FloatField(blank=True, null=True)),
                ('cabecalho_medida_c', models.CharField(blank=True, max_length=10, null=True)),
                ('medida_c', models.FloatField(blank=True, null=True)),
                ('cabecalho_medida_d', models.CharField(blank=True, max_length=10, null=True)),
                ('medida_d', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
