# Generated by Django 5.0.6 on 2025-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0003_infoadicionaisinspecaoestamparia_dados_exec_inspecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicionaisinspecaoestamparia',
            name='ficha',
            field=models.ImageField(blank=True, null=True, upload_to='ficha_estamparia/'),
        ),
    ]
