# Generated by Django 4.2.15 on 2025-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0004_alter_infoadicionaisinspecaoestamparia_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='destino_a',
            field=models.CharField(blank=True, choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_d',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
