# Generated by Django 4.2.15 on 2025-03-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0005_medidasinspecaoestamparia_destino_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='destino_b',
            field=models.CharField(blank=True, choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='destino_c',
            field=models.CharField(blank=True, choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medidasinspecaoestamparia',
            name='destino_d',
            field=models.CharField(blank=True, choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=30, null=True),
        ),
    ]
