# Generated by Django 4.2.15 on 2025-03-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0006_medidasinspecaoestamparia_destino_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoadicionaisinspecaoestamparia',
            name='destino',
        ),
    ]
