# Generated by Django 4.2.15 on 2025-03-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0026_alter_reinspecao_reinspecionado'),
        ('apontamento_estamparia', '0007_remove_infoadicionaisinspecaoestamparia_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosNaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_nao_conformidade', models.IntegerField()),
                ('destino', models.CharField(choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=10)),
                ('causas', models.ManyToManyField(blank=True, related_name='causas_nao_conformidade_estamparia', to='inspecao.causas')),
            ],
        ),
        migrations.RemoveField(
            model_name='infoadicionaisinspecaoestamparia',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='destino_a',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='destino_b',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='destino_c',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='destino_d',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_a',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_b',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_c',
        ),
        migrations.RemoveField(
            model_name='medidasinspecaoestamparia',
            name='qtd_afetada_d',
        ),
        migrations.RemoveField(
            model_name='infoadicionaisinspecaoestamparia',
            name='motivo_mortas',
        ),
        migrations.CreateModel(
            name='ImagemNaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='nao_conformidade_estamparia/')),
                ('nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='apontamento_estamparia.dadosnaoconformidade')),
            ],
        ),
        migrations.AddField(
            model_name='dadosnaoconformidade',
            name='informacoes_adicionais_estamparia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apontamento_estamparia.infoadicionaisinspecaoestamparia'),
        ),
        migrations.AddField(
            model_name='infoadicionaisinspecaoestamparia',
            name='motivo_mortas',
            field=models.ManyToManyField(blank=True, related_name='motivo_morta_estamparia', to='inspecao.causas'),
        ),
    ]
