# Generated by Django 4.2.15 on 2025-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0010_remove_infoadicionaisinspecaoestamparia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasinspecaoestamparia',
            name='cabecalho_medida_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medidasinspecaoestamparia',
            name='cabecalho_medida_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medidasinspecaoestamparia',
            name='cabecalho_medida_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medidasinspecaoestamparia',
            name='cabecalho_medida_d',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
