# Generated by Django 5.0.6 on 2025-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0011_alter_medidasinspecaoestamparia_cabecalho_medida_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadicionaisinspecaoestamparia',
            name='autoinspecao_noturna',
            field=models.BooleanField(default=False),
        ),
    ]
