# Generated by Django 4.2.16 on 2025-10-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0038_alter_dadosexecucaoinspecao_data_execucao'),
        ('apontamento_estamparia', '0012_infoadicionaisinspecaoestamparia_autoinspecao_noturna'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadicionaisinspecaoestamparia',
            name='inspecao_finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infoadicionaisinspecaoestamparia',
            name='dados_exec_inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_adicionais_estamparia', to='inspecao.dadosexecucaoinspecao'),
        ),
    ]
