# Generated by Django 4.2.15 on 2025-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0012_infoadicionaisinspecaoestamparia_autoinspecao_noturna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicionaisinspecaoestamparia',
            name='inspecao_completa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
