# Generated by Django 4.2.15 on 2025-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0013_alter_infoadicionaisinspecaoestamparia_inspecao_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadicionaisinspecaoestamparia',
            name='inspecao_finalizada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
