# Generated by Django 4.2.16 on 2025-10-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0038_alter_dadosexecucaoinspecao_data_execucao'),
        ('apontamento_estamparia', '0013_infoadicionaisinspecaoestamparia_inspecao_finalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicionaisinspecaoestamparia',
            name='dados_exec_inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.dadosexecucaoinspecao'),
        ),
    ]
