# Generated by Django 4.2.16 on 2025-10-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0014_alter_infoadicionaisinspecaoestamparia_dados_exec_inspecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheMedidaEstamparia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('conforme', models.BooleanField(default=True)),
                ('medida_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_estamparia', to='apontamento_estamparia.medidasinspecaoestamparia')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
