# Generated by Django 4.2.16 on 2025-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0015_detalhemedidaestamparia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhemedidaestamparia',
            name='amostra',
            field=models.IntegerField(default=1),
        ),
    ]
