# Generated by Django 4.2.16 on 2026-02-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apontamento_estamparia', '0015_infoadicionaisinspecaoestamparia_qtd_mortas_inicio_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='apontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='chave_apontamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='data_apontamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='resp_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_estamparia_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
