# Generated by Django 4.2.16 on 2026-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0016_pecasordem_apontado_pecasordem_chave_apontamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='tipo_apontamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pecasordem',
            name='data_apontamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
