# Generated by Django 4.2.16 on 2026-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_estamparia', '0017_pecasordem_tipo_apontamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='erro_apontamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
