# Generated by Django 4.2.16 on 2026-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_almox', '0002_regraslaalmox'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraslaalmox',
            name='cor',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
    ]
