# Generated by Django 4.2.15 on 2024-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0007_delete_pecaprocesso'),
        ('apontamento_serra', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_serra', to='core.ordem'),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_ordem_serra', to='cadastro.pecas'),
        ),
    ]
