# Generated by Django 4.2.15 on 2024-12-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecasordem',
            old_name='quantidade',
            new_name='qtd_boa',
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='qtd_planejada',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
