# Generated by Django 4.2.15 on 2025-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0005_pecasordem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasordem',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
