# Generated by Django 5.2.4 on 2025-07-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0006_alter_pecasordem_data'),
        ('inspecao', '0029_alter_infoadicionaisexectuboscilindros_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAdicionaisSerraUsinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspecao_completa', models.BooleanField(default=False)),
                ('autoinspecao_noturna', models.BooleanField(default=False)),
                ('ficha', models.ImageField(blank=True, null=True, upload_to='fichas_inspecao/')),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('dados_exec_inspecao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_adicionais', to='inspecao.dadosexecucaoinspecao')),
            ],
            options={
                'verbose_name': 'Informação Adicional',
                'verbose_name_plural': 'Informações Adicionais',
            },
        ),
        migrations.CreateModel(
            name='MedidasProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_processo', models.CharField(choices=[('serra', 'Serra'), ('usinagem', 'Usinagem'), ('furacao', 'Furação')], max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_processo', to='inspecao.dadosexecucaoinspecao')),
                ('info_adicionais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='apontamento_serra.infoadicionaisserrausinagem')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
