# Generated by Django 5.0.6 on 2025-07-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0007_infoadicionaisserrausinagem_medidasprocesso'),
        ('inspecao', '0030_inspecao_pecas_ordem_serra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedidasProcesso',
            new_name='MedidasProcessoSerraUsinagem',
        ),
        migrations.CreateModel(
            name='DetalheMedidaSerraUsinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('medida_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='apontamento_serra.medidasprocessoserrausinagem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
