# Generated by Django 5.0.6 on 2025-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0008_rename_medidasprocesso_medidasprocessoserrausinagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhemedidaserrausinagem',
            name='amostra',
            field=models.IntegerField(default=1),
        ),
    ]
