# Generated by Django 5.0.6 on 2025-07-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0009_detalhemedidaserrausinagem_amostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhemedidaserrausinagem',
            name='conforme',
            field=models.BooleanField(default=True),
        ),
    ]
