# Generated by Django 5.0.6 on 2025-07-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0010_detalhemedidaserrausinagem_conforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoadicionaisserrausinagem',
            name='autoinspecao_noturna',
        ),
    ]
