# Generated by Django 5.0.6 on 2025-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0011_remove_infoadicionaisserrausinagem_autoinspecao_noturna'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadicionaisserrausinagem',
            name='inspecao_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
