# Generated by Django 5.2.4 on 2025-08-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0012_infoadicionaisserrausinagem_inspecao_finalizada'),
        ('inspecao', '0030_inspecao_pecas_ordem_serra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosNaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_nao_conformidade', models.IntegerField()),
                ('destino', models.CharField(choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], max_length=10)),
                ('causas', models.ManyToManyField(blank=True, related_name='causas_nao_conformidade_serra_usinagem', to='inspecao.causas')),
                ('informacoes_adicionais_serra_usinagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apontamento_serra.infoadicionaisserrausinagem')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemNaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='nao_conformidade_serra_usinagem/')),
                ('nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='apontamento_serra.dadosnaoconformidade')),
            ],
        ),
    ]
