# Generated by Django 5.2.4 on 2025-08-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0013_dadosnaoconformidade_imagemnaoconformidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemnaoconformidade',
            name='nao_conformidade',
        ),
        migrations.DeleteModel(
            name='DadosNaoConformidade',
        ),
        migrations.DeleteModel(
            name='ImagemNaoConformidade',
        ),
    ]
