# Generated by Django 4.2.15 on 2025-06-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0031_remove_operador_maquina_operador_maquinas'),
        ('core', '0049_ordem_ordem_prioridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntosInspecionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=55)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=255)),
                ('qtd_planejada', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
                ('qtd_boa', models.FloatField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_produzido_solda', to='cadastro.operador')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_solda', to='core.ordem')),
                ('processo_ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_ordem_solda', to='core.ordemprocesso')),
            ],
        ),
    ]
