# Generated by Django 4.2.15 on 2025-08-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0039_operador_status'),
        ('apontamento_solda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecasordem',
            old_name='operador',
            new_name='operador_final',
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='operador_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_inicio_solda', to='cadastro.operador'),
        ),
    ]
