# Generated by Django 4.2.15 on 2024-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=255)),
                ('quantidade', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
            ],
        ),
    ]
