# Generated by Django 4.2.15 on 2025-03-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_ordem_motivo_retirar_sequenciada'),
        ('apontamento_corte', '0005_pecasordem_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pecasordem',
            unique_together={('ordem', 'peca')},
        ),
    ]
