# Generated by Django 4.2.15 on 2025-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_corte', '0006_alter_pecasordem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='apontamento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='obs_apontamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
