# Generated by Django 4.2.15 on 2025-11-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apontamento_corte', '0007_pecasordem_apontamento_pecasordem_obs_apontamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='apontado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='apontado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecasordem_apontadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
