# Generated by Django 4.2.16 on 2026-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_corte', '0008_pecasordem_apontamento_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasordem',
            name='peca',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
