# Generated by Django 4.2.16 on 2026-08-26 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0079_rota_cadastro_configuracoes'),
        ('apontamento_corte', '0009_alter_pecasordem_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaNaoConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=255)),
                ('quantidade', models.FloatField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('qtd_sucata', models.FloatField(blank=True, null=True)),
                ('qtd_recuperada', models.FloatField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_nao_conforme', to='core.ordem')),
                ('ordem_recuperada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ordem')),
                ('ordem_sucata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ordem')),
                ('peca_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformes', to='apontamento_corte.pecasordem')),
                ('resp_decisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
