# Generated by Django 4.2.16 on 2026-04-27 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0004_cargaliberadaitem_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_carga', models.DateField()),
                ('cliente', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='linkacompanhamento',
            constraint=models.UniqueConstraint(fields=('data_carga', 'cliente'), name='uq_link_acompanhamento_data_cliente'),
        ),
    ]
