# Generated by Django 4.2.16 on 2026-04-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0005_cargaliberada_data_sugerida_planejamento'),
        ('cargas', '0005_link_acompanhamento'),
    ]

    operations = [
    ]
