# Generated by Django 4.2.15 on 2025-01-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0013_conjuntos'),
        ('core', '0012_alter_ordem_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_planejada', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
                ('qtd_boa', models.FloatField(default=0)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_ordem_prod_especiais', to='cadastro.conjuntos')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_prod_especiais', to='core.ordem')),
            ],
        ),
    ]
