# Generated by Django 4.2.15 on 2025-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_prod_especiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
