# Generated by Django 4.2.15 on 2025-08-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0054_ordemprocesso_comentario_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('status_confirmacao', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Confirmado'), ('erro', 'Erro identificado')], default='pendente', max_length=50)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='apontamento_exped.carga')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmou_pacotes', to='core.profile')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_peca', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apontamento_exped.pacote')),
            ],
        ),
    ]
