# Generated by Django 4.2.15 on 2025-08-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_ordemprocesso_comentario_extra'),
        ('apontamento_exped', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_verificacao', models.DateTimeField(auto_now_add=True)),
                ('tudo_correto', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('pacote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao', to='apontamento_exped.pacote')),
                ('verificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
    ]
