# Generated by Django 4.2.15 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0002_verificacaopacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Confirmado'), ('erro', 'Erro identificado')], default='pendente', max_length=50),
        ),
    ]
