# Generated by Django 4.2.15 on 2025-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0003_carga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='carga',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carga',
            name='carreta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
