# Generated by Django 4.2.15 on 2025-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0004_carga_carga_carga_carreta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='obs_pacote',
            field=models.TextField(blank=True),
        ),
    ]
