# Generated by Django 4.2.15 on 2025-08-27 14:29

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0005_carga_obs_pacote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='carreta',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='carga',
            name='data_carga',
            field=models.DateField(default=datetime.date(2025, 8, 27)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarretaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreta', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carretas', to='apontamento_exped.carga')),
            ],
        ),
    ]
