# Generated by Django 4.2.15 on 2025-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0006_rename_carreta_carga_cliente_carga_data_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='data_carga',
            field=models.DateField(blank=True, null=True),
        ),
    ]
