# Generated by Django 4.2.15 on 2025-08-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0007_alter_carga_data_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='numero',
        ),
        migrations.AddField(
            model_name='pacote',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
