# Generated by Django 4.2.15 on 2025-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0008_remove_pacote_numero_pacote_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempacote',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itempacote',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
