# Generated by Django 4.2.15 on 2025-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0009_alter_itempacote_cor_alter_itempacote_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='stage',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('apontamento', 'Apontamento'), ('verificacao', 'Verificação'), ('despachado', 'Despachado')], default='planejamento', max_length=50),
        ),
    ]
