# Generated by Django 4.2.15 on 2025-09-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0010_carga_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='imagem_pacote/')),
                ('pacote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_imagem', to='apontamento_exped.pacote')),
            ],
        ),
    ]
