# Generated by Django 4.2.15 on 2025-09-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0011_imagempacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempacote',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_imagem', to='apontamento_exped.pacote'),
        ),
    ]
