# Generated by Django 4.2.15 on 2025-09-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_rotaacesso_app'),
        ('apontamento_exped', '0012_alter_imagempacote_pacote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacote',
            old_name='data_confirmacao',
            new_name='data_confirmacao_expedicao',
        ),
        migrations.RenameField(
            model_name='pacote',
            old_name='status_confirmacao',
            new_name='status_confirmacao_expedicao',
        ),
        migrations.RemoveField(
            model_name='pacote',
            name='confirmado_por',
        ),
        migrations.AddField(
            model_name='pacote',
            name='confirmado_por_expedicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmou_pacotes_expedicao', to='core.profile'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='confirmado_por_qualidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmou_pacotes_qualidade', to='core.profile'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='data_confirmacao_qualidade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='obs_expedicao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='obs_qualidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='status_confirmacao_qualidade',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Confirmado'), ('erro', 'Erro identificado')], default='pendente', max_length=50),
        ),
    ]
