# Generated by Django 4.2.15 on 2025-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0013_rename_data_confirmacao_pacote_data_confirmacao_expedicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagempacote',
            name='stage',
            field=models.CharField(choices=[('verificacao', 'Verificação'), ('despachado', 'Despachado')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
