# Generated by Django 4.2.15 on 2025-09-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0014_imagempacote_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempacote',
            name='codigo_peca',
        ),
        migrations.RemoveField(
            model_name='itempacote',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='itempacote',
            name='descricao',
        ),
        migrations.CreateModel(
            name='PendenciasPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('qt_necessaria', models.IntegerField()),
                ('carreta_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreta_carga', to='apontamento_exped.carretacarga')),
            ],
        ),
        migrations.AddField(
            model_name='itempacote',
            name='codigo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_item_pacote', to='apontamento_exped.pendenciaspacote'),
            preserve_default=False,
        ),
    ]
