# Generated by Django 4.2.15 on 2025-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0015_remove_itempacote_codigo_peca_remove_itempacote_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempacote',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-26 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendenciaspacote',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-26 00:00:00'),
            preserve_default=False,
        ),
    ]
