# Generated by Django 4.2.15 on 2025-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0016_itempacote_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempacote',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_item_pacote', to='apontamento_exped.pendenciaspacote'),
        ),
    ]
