# Generated by Django 4.2.15 on 2026-03-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0018_alter_itempacote_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempacote',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_item_pacote', to='apontamento_exped.pendenciaspacote'),
        ),
        migrations.AddField(
            model_name='itempacote',
            name='codigo_informado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempacote',
            name='descricao_informada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempacote',
            name='fora_planejado',
            field=models.BooleanField(default=False),
        ),
    ]

