# Generated by Django 4.2.16 on 2026-04-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0019_itempacote_fora_planejado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedoresCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_pneu', models.CharField(blank=True, max_length=255)),
                ('fornecedor_cilindro', models.CharField(blank=True, max_length=255)),
                ('fornecedor_roda', models.CharField(blank=True, max_length=255)),
                ('carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='apontamento_exped.carga')),
            ],
        ),
    ]
