# Generated by Django 4.2.16 on 2026-04-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0020_fornecedorescarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorItemCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=255)),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_itens', to='apontamento_exped.carga')),
            ],
            options={
                'unique_together': {('carga', 'tipo', 'codigo')},
            },
        ),
        migrations.DeleteModel(
            name='FornecedoresCarga',
        ),
    ]
