# Generated by Django 4.2.16 on 2026-09-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_rota_cadastro_tubos'),
        ('apontamento_exped', '0022_carga_data_despachado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BipagemPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bipagem', models.DateTimeField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('bipado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('pacote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bipagem', to='apontamento_exped.pacote')),
            ],
        ),
    ]
