# Generated by Django 4.2.16 on 2026-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_exped', '0023_bipagempacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='stage',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('apontamento', 'Apontamento'), ('verificacao', 'Verificação'), ('bipagem', 'Bipagem'), ('despachado', 'Despachado')], default='planejamento', max_length=50),
        ),
    ]
