# Generated by Django 4.2.16 on 2026-06-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conferenciapedido',
            name='conf_pedido_chave_deal_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendenciaimportacaoplanilha',
            name='pend_import_emissao_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendenciaimportacaoplanilha',
            name='pend_import_chave_neg_idx',
        ),
    ]
