# Generated by Django 4.2.15 on 2024-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('setor', models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoInterrupcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('setor', models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=20)),
                ('setor', models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('materia_prima', models.CharField(blank=True, max_length=100, null=True)),
                ('comprimento', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pecas',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo'),
        ),
    ]
