# Generated by Django 4.2.15 on 2024-10-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('materia_prima', models.CharField(blank=True, max_length=100, null=True)),
                ('comprimento', models.FloatField(blank=True, null=True)),
                ('setor', models.ManyToManyField(related_name='pecas_setor', to='cadastro.setor')),
            ],
        ),
        migrations.CreateModel(
            name='PecaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecas')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.processo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=20)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_setor', to='cadastro.setor')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoInterrupcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('setor', models.ManyToManyField(related_name='motivo_setor', to='cadastro.setor')),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='setor',
            field=models.ManyToManyField(related_name='maquina_setor', to='cadastro.setor'),
        ),
        migrations.AddConstraint(
            model_name='pecas',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo'),
        ),
        migrations.AlterUniqueTogether(
            name='pecaprocesso',
            unique_together={('peca', 'processo', 'ordem')},
        ),
    ]
