# Generated by Django 5.0.1 on 2024-09-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("usinagem", "Usinagem"),
                            ("serra", "Serra"),
                            ("estamparia", "Estamparia"),
                            ("corte", "Corte"),
                            ("montagem", "Montagem"),
                            ("pintura", "Pintura"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotivoInterrupcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("usinagem", "Usinagem"),
                            ("serra", "Serra"),
                            ("estamparia", "Estamparia"),
                            ("corte", "Corte"),
                            ("montagem", "Montagem"),
                            ("pintura", "Pintura"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=20)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("usinagem", "Usinagem"),
                            ("serra", "Serra"),
                            ("estamparia", "Estamparia"),
                            ("corte", "Corte"),
                            ("montagem", "Montagem"),
                            ("pintura", "Pintura"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PecaProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Pecas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "materia_prima",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comprimento", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PecaMaquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.maquina",
                    ),
                ),
                (
                    "peca_processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.pecaprocesso",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.AddConstraint(
            model_name="pecas",
            constraint=models.UniqueConstraint(
                fields=("codigo",), name="unique_codigo"
            ),
        ),
        migrations.AddField(
            model_name="pecaprocesso",
            name="peca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastro.pecas"
            ),
        ),
        migrations.AddField(
            model_name="pecaprocesso",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastro.processo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pecamaquina",
            unique_together={("peca_processo", "maquina")},
        ),
        migrations.AlterUniqueTogether(
            name="pecaprocesso",
            unique_together={("peca", "processo", "ordem")},
        ),
    ]
