# Generated by Django 4.2.15 on 2024-09-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pecaprocesso',
            unique_together={('peca', 'processo', 'ordem')},
        ),
    ]
