# Generated by Django 4.2.15 on 2024-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pecaprocesso_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pecaprocessomaquina',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pecaprocessomaquina',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='pecaprocessomaquina',
            name='peca_processo',
        ),
        migrations.AlterField(
            model_name='pecas',
            name='processos',
            field=models.ManyToManyField(related_name='pecas', to='cadastro.processo'),
        ),
    ]
