# Generated by Django 4.2.15 on 2024-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pecas_descricao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pecas',
            name='unique_codigo',
        ),
        migrations.AddField(
            model_name='pecas',
            name='setor',
            field=models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], default='serra', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pecas',
            constraint=models.UniqueConstraint(fields=('codigo', 'setor'), name='unique_codigo'),
        ),
    ]
