# Generated by Django 4.2.15 on 2024-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pecaprocesso_processo_delete_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecas',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='setor',
            field=models.ManyToManyField(blank=True, related_name='pecas_setor', to='cadastro.setor'),
        ),
    ]
