# Generated by Django 4.2.15 on 2024-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_pecas_unique_codigo_pecas_setor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pecas',
            name='unique_codigo',
        ),
        migrations.AlterField(
            model_name='pecas',
            name='setor',
            field=models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pecas',
            constraint=models.UniqueConstraint(fields=('codigo', 'setor'), name='unique_codigo_setor'),
        ),
    ]
