# Generated by Django 4.2.15 on 2024-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pecas_descricao_alter_pecas_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
