# Generated by Django 4.2.15 on 2024-09-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_pecamaquina_and_more'),
        ('apontamento', '0002_alter_planejamento_peca_processo_maquina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PecaProcessoMaquina',
        ),
        migrations.AddField(
            model_name='pecamaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina'),
        ),
        migrations.AddField(
            model_name='pecamaquina',
            name='peca_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecaprocesso'),
        ),
        migrations.AlterUniqueTogether(
            name='pecamaquina',
            unique_together={('peca_processo', 'maquina')},
        ),
    ]
