# Generated by Django 4.2.15 on 2024-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_pecas_apelido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecas',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
