# Generated by Django 4.2.15 on 2024-12-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_pecas_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecaprocesso',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina'),
        ),
    ]
