# Generated by Django 4.2.15 on 2024-12-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_pecaprocesso_maquina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PecaProcesso',
        ),
    ]
