# Generated by Django 4.2.15 on 2024-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_delete_pecaprocesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
