# Generated by Django 4.2.15 on 2024-12-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='cadastro.setor'),
            preserve_default=False,
        ),
    ]
