# Generated by Django 4.2.15 on 2024-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_mp_setor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operador',
            constraint=models.UniqueConstraint(fields=('matricula', 'setor'), name='operador_setor_unique'),
        ),
    ]
