# Generated by Django 4.2.15 on 2024-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_operador_operador_setor_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='matricula',
            field=models.CharField(max_length=10),
        ),
    ]
