# Generated by Django 4.2.15 on 2024-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_operador_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espessura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
