# Generated by Django 4.2.15 on 2025-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_espessura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
