# Generated by Django 4.2.15 on 2025-01-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_conjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.setor')),
            ],
        ),
    ]
