# Generated by Django 4.2.15 on 2025-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivointerrupcao',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
