# Generated by Django 4.2.15 on 2025-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_motivointerrupcao_visivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('setor', models.ManyToManyField(related_name='motivo_exclusao_setor', to='cadastro.setor')),
            ],
        ),
    ]
