# Generated by Django 4.2.15 on 2025-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_motivomaquinaparada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
