# Generated by Django 4.2.15 on 2025-02-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_maquina_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='setor',
        ),
        migrations.AddField(
            model_name='maquina',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maquina_setor', to='cadastro.setor'),
            preserve_default=False,
        ),
    ]
