# Generated by Django 4.2.15 on 2025-02-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_remove_maquina_setor_maquina_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carretas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='conjuntos',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conjuntos',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='ConjuntoCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.carretas')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.conjuntos')),
            ],
        ),
        migrations.AddField(
            model_name='conjuntos',
            name='carreta',
            field=models.ManyToManyField(blank=True, through='cadastro.ConjuntoCarreta', to='cadastro.carretas'),
        ),
        migrations.AddConstraint(
            model_name='conjuntocarreta',
            constraint=models.UniqueConstraint(fields=('conjunto', 'carreta'), name='unique_conjunto_carreta'),
        ),
    ]
