# Generated by Django 4.2.15 on 2025-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_carretas_conjuntos_quantidade_alter_conjuntos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntos',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
    ]
