# Generated by Django 5.0.6 on 2025-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_alter_conjuntos_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasEstanqueidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('tanque', 'Tanque'), ('tubo', 'Tubo'), ('cilindro', 'Cilindro')], max_length=10)),
            ],
        ),
    ]
