# Generated by Django 4.2.15 on 2025-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_remove_pecas_unique_codigo_pecas_conjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
