# Generated by Django 4.2.15 on 2025-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_alter_maquina_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipo_pintura',
            field=models.CharField(blank=True, choices=[('PO', 'PÓ'), ('PU', 'PU')], max_length=5, null=True),
        ),
    ]
