# Generated by Django 4.2.15 on 2025-03-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_maquina_tipo_pintura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='tipo_pintura',
        ),
    ]
