# Generated by Django 4.2.15 on 2025-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_pecasestanqueidade'),
        ('cadastro', '0025_remove_maquina_tipo_pintura'),
    ]

    operations = [
    ]
