# Generated by Django 4.2.15 on 2025-04-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_merge_20250324_1554'),
        ('cadastro', '0026_merge_20250324_1601'),
    ]

    operations = [
    ]
