# Generated by Django 4.2.15 on 2025-04-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_merge_20250408_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='processo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_maquina_1', to='cadastro.maquina'),
        ),
    ]
