# Generated by Django 5.0.6 on 2025-05-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0029_alter_pecas_conjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='maquina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_maquina', to='cadastro.maquina'),
        ),
    ]
