# Generated by Django 5.0.6 on 2025-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_operador_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='maquina',
        ),
        migrations.AddField(
            model_name='operador',
            name='maquinas',
            field=models.ManyToManyField(blank=True, related_name='operadores', to='cadastro.maquina'),
        ),
    ]
