# Generated by Django 4.2.15 on 2025-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0031_remove_operador_maquina_operador_maquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('nome', 'setor'), name='unique_nome_setor_maquina'),
        ),
    ]
