# Generated by Django 4.2.15 on 2025-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0032_alter_maquina_nome_maquina_unique_nome_setor_maquina'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maquina',
            name='unique_nome_setor_maquina',
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('nome', 'setor', 'tipo'), name='unique_nome_setor_maquina_tipo'),
        ),
    ]
