# Generated by Django 4.2.15 on 2025-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0033_remove_maquina_unique_nome_setor_maquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarretasExplodidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_peca', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao_peca', models.CharField(blank=True, max_length=255, null=True)),
                ('mp', models.CharField(blank=True, max_length=255, null=True)),
                ('total_peca', models.CharField(blank=True, max_length=10, null=True)),
                ('primeiro_processo', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_processo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
