# Generated by Django 4.2.15 on 2025-07-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0034_carretasexplodidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carretasexplodidas',
            old_name='mp',
            new_name='mp_peca',
        ),
        migrations.AddField(
            model_name='carretasexplodidas',
            name='conjunto_peca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
