# Generated by Django 4.2.15 on 2025-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0035_rename_mp_carretasexplodidas_mp_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carretasexplodidas',
            name='carreta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
