# Generated by Django 4.2.15 on 2025-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0036_carretasexplodidas_carreta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carretasexplodidas',
            name='conjunto_peca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
