# Generated by Django 4.2.15 on 2025-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0037_alter_carretasexplodidas_conjunto_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivointerrupcao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
