# Generated by Django 4.2.16 on 2025-08-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0038_alter_motivointerrupcao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
    ]
