# Generated by Django 4.2.15 on 2025-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0039_operador_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carretasexplodidas',
            name='grupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
