# Generated by Django 4.2.15 on 2026-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0040_carretasexplodidas_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carretasexplodidas',
            name='grupo1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carretasexplodidas',
            name='grupo2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
