# Generated by Django 4.2.15 on 2026-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0041_carretasexplodidas_grupo1_carretasexplodidas_grupo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='carretasexplodidas',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
