# Generated by Django 4.2.16 on 2026-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0044_alter_mp_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
