# Generated by Django 4.2.16 on 2026-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0053_espessurachapa_largura_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(help_text="Numero com DDI, sem '+' e sem espacos (ex: 5511999998888)", max_length=20)),
                ('tipo_notificacao', models.CharField(choices=[('falta_peca', 'Falta de peça')], default='falta_peca', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
