# Generated by Django 4.2.16 on 2026-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0054_destinatarionotificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarionotificacao',
            name='tipo_notificacao',
            field=models.CharField(choices=[('falta_peca', 'Falta de peça'), ('notificacao_qualidade', 'Notificação de qualidade')], default='falta_peca', max_length=30),
        ),
    ]
