# Generated by Django 4.2.16 on 2026-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0055_alter_destinatarionotificacao_tipo_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
