# Generated by Django 4.2.15 on 2025-02-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_ordem_cor_ordem_data_carga_ordem_setor_conjunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=255)),
                ('qtd_planejada', models.FloatField()),
                ('qtd_morta', models.FloatField(default=0)),
                ('qtd_boa', models.FloatField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pecas_montagem', to='core.ordem')),
            ],
        ),
    ]
