# Generated by Django 4.2.15 on 2025-02-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_alter_conjuntos_codigo'),
        ('apontamento_montagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_produzido_montagem', to='cadastro.operador'),
        ),
    ]
