# Generated by Django 4.2.15 on 2025-02-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_ordem_setor_conjunto'),
        ('apontamento_montagem', '0002_pecasordem_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='processo_ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_ordem_montagem', to='core.ordemprocesso'),
        ),
    ]
