# Generated by Django 5.0.6 on 2025-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_montagem', '0003_pecasordem_processo_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntosInspecionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=55)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
