# Generated by Django 4.2.16 on 2026-05-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0046_conjuntos_add_ativo'),
        ('apontamento_montagem', '0004_conjuntosinspecionados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaktCelulaExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='takt_excluida', to='cadastro.maquina')),
            ],
        ),
    ]
