# Generated by Django 4.2.15 on 2024-09-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apontamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('interrompido', 'Interrompido'), ('finalizado', 'Finalizado'), ('parcial', 'Finalizado Parcialmente')], default='iniciado', max_length=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamento_operador', to='cadastro.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_planejada', models.DateField()),
                ('tipo_planejamento', models.CharField(choices=[('planejamento', 'Planejamento'), ('fora_do_planejamento', 'Fora do planejamento')], default='planejamento', max_length=20)),
                ('status_andamento', models.CharField(choices=[('aguardando_iniciar', 'Aguardando iniciar'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('interrompida', 'Interrompida')], default='aguardando_iniciar', max_length=20)),
                ('tamanho_vara', models.CharField(blank=True, max_length=20, null=True)),
                ('quantidade_vara', models.PositiveIntegerField(blank=True, null=True)),
                ('setor', models.CharField(choices=[('usinagem', 'Usinagem'), ('serra', 'Serra'), ('estamparia', 'Estamparia'), ('corte', 'Corte'), ('montagem', 'Montagem'), ('pintura', 'Pintura')], max_length=20)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_maquina', to='cadastro.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('quantidade_produzida', models.PositiveIntegerField(default=0)),
                ('quantidade_morta', models.PositiveIntegerField(default=0)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_peca', to='cadastro.pecas')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_planejadas', to='apontamento.planejamento')),
            ],
        ),
        migrations.CreateModel(
            name='Interrupcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interrupcao', models.DateTimeField()),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrupcoes', to='apontamento.apontamento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.motivointerrupcao')),
            ],
        ),
        migrations.AddField(
            model_name='apontamento',
            name='planejamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamento_planejamento', to='apontamento.planejamento'),
        ),
    ]
