# Generated by Django 5.0.1 on 2024-09-28 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apontamento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planejamento",
            name="peca_processo_maquina",
        ),
        migrations.RemoveField(
            model_name="planejamento",
            name="processo",
        ),
    ]
