# Generated by Django 4.2.15 on 2024-10-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_setor', to='cadastro.setor'),
            preserve_default=False,
        ),
    ]
