# Generated by Django 4.2.15 on 2024-09-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_pecamaquina_and_more'),
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='peca_processo_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecamaquina'),
        ),
    ]
