# Generated by Django 4.2.15 on 2024-09-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='mp_usada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
