# Generated by Django 4.2.15 on 2024-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pecaprocesso_processo_delete_processo'),
        ('apontamento', '0003_planejamentopeca_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveIntegerField(editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pecas', models.ManyToManyField(related_name='ordens_padroes', to='cadastro.pecaprocesso')),
            ],
        ),
    ]
