# Generated by Django 5.0.1 on 2024-09-28 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apontamento", "0003_remove_planejamento_setor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planejamento",
            name="maquina",
        ),
    ]
