# Generated by Django 4.2.15 on 2024-10-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0004_ordempadrao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordempadrao',
            name='nome',
        ),
    ]
