# Generated by Django 4.2.15 on 2024-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0005_remove_ordempadrao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='quantidade_vara',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
