# Generated by Django 4.2.16 on 2026-07-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChatAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_id', models.CharField(max_length=36)),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=10)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_assistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em'],
                'indexes': [models.Index(fields=['usuario', 'sessao_id', 'criada_em'], name='assistente__usuario_5cb9ee_idx')],
            },
        ),
    ]
