# Generated by Django 4.2.16 on 2026-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('dados_hash', models.CharField(max_length=64)),
                ('analise', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['codigo', 'dados_hash'], name='compras_ana_codigo_cb833d_idx')],
            },
        ),
    ]
