# Generated by Django 5.0.6 on 2025-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinspecao',
            name='reinspecionado',
            field=models.BooleanField(default=False),
        ),
    ]
