# Generated by Django 5.0.6 on 2025-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0002_reinspecao_reinspecionado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causas',
            options={'verbose_name': 'Causa'},
        ),
        migrations.AlterField(
            model_name='causas',
            name='setor',
            field=models.CharField(choices=[('pintura', 'Pintura'), ('montagem', 'Montagem'), ('estamparia', 'Estamparia'), ('tubos cilindros', 'Tubos e Cilindros'), ('tanque', 'Tanque')], max_length=40),
        ),
        migrations.RemoveField(
            model_name='causasnaoconformidade',
            name='causa',
        ),
        migrations.AddField(
            model_name='causasnaoconformidade',
            name='causa',
            field=models.ManyToManyField(blank=True, related_name='causas_nao_conformidade', to='inspecao.causas'),
        ),
    ]
