# Generated by Django 5.0.6 on 2025-03-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0003_alter_causas_options_alter_causas_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causasnaoconformidade',
            name='foto',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dadosexecucaoinspecao',
            name='num_execucao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArquivoCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='causas_nao_conformidade/')),
                ('causa_nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='inspecao.causasnaoconformidade')),
            ],
        ),
    ]
