# Generated by Django 5.0.6 on 2025-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0004_alter_causasnaoconformidade_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causasnaoconformidade',
            name='foto',
        ),
    ]
