# Generated by Django 5.0.6 on 2025-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0005_remove_causasnaoconformidade_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocausa',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='causas_nao_conformidade/'),
        ),
    ]
