# Generated by Django 5.0.6 on 2025-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0006_alter_arquivocausa_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosexecucaoinspecao',
            name='data_execucao',
            field=models.DateTimeField(),
        ),
    ]
