# Generated by Django 5.0.6 on 2025-03-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0007_alter_dadosexecucaoinspecao_data_execucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinspecao',
            name='dados_execucao',
        ),
        migrations.AddField(
            model_name='reinspecao',
            name='inspecao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecao'),
        ),
    ]
