# Generated by Django 5.0.6 on 2025-03-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0008_remove_reinspecao_dados_execucao_reinspecao_inspecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspecao',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecao'),
        ),
    ]
