# Generated by Django 5.0.6 on 2025-03-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0009_alter_reinspecao_inspecao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoadicionaisexectuboscilindros',
            old_name='nao_conformidade',
            new_name='nao_conformidade_retrabalho',
        ),
        migrations.RemoveField(
            model_name='infoadicionaisexectuboscilindros',
            name='foto_ficha',
        ),
        migrations.AddField(
            model_name='infoadicionaisexectuboscilindros',
            name='ficha',
            field=models.ImageField(blank=True, null=True, upload_to='ficha_tubos_cilindros/'),
        ),
        migrations.AlterField(
            model_name='dadosexecucaoinspecaoestanqueidade',
            name='num_execucao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
