# Generated by Django 5.0.6 on 2025-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0010_rename_nao_conformidade_infoadicionaisexectuboscilindros_nao_conformidade_retrabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinspecaoestanqueidade',
            name='reinspecionado',
            field=models.BooleanField(default=False),
        ),
    ]
