# Generated by Django 5.0.6 on 2025-03-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_pecasestanqueidade'),
        ('inspecao', '0011_reinspecaoestanqueidade_reinspecionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecaoestanqueidade',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inspecaoestanqueidade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='inspecaoestanqueidade',
            name='tipo_inspecao',
        ),
        migrations.AddField(
            model_name='inspecaoestanqueidade',
            name='peca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecasestanqueidade'),
        ),
    ]
