# Generated by Django 5.0.6 on 2025-03-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_pecasestanqueidade'),
        ('inspecao', '0013_alter_inspecaoestanqueidade_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecaoestanqueidade',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecasestanqueidade'),
        ),
    ]
