# Generated by Django 5.0.6 on 2025-03-14 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0016_alter_inspecaoestanqueidade_peca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinspecaoestanqueidade',
            name='dados_exec_inspecao',
        ),
        migrations.AddField(
            model_name='reinspecaoestanqueidade',
            name='inspecao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecaoestanqueidade'),
        ),
    ]
