# Generated by Django 5.0.6 on 2025-03-14 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0017_remove_reinspecaoestanqueidade_dados_exec_inspecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspecaoestanqueidade',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecaoestanqueidade'),
        ),
    ]
