# Generated by Django 5.0.6 on 2025-03-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_pecasestanqueidade'),
        ('inspecao', '0018_alter_reinspecaoestanqueidade_inspecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecaoestanqueidade',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pecasestanqueidade'),
        ),
    ]
