# Generated by Django 5.0.6 on 2025-03-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0020_rename_nao_conformidade_retrabalho_infoadicionaisexectuboscilindros_nao_conformidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausasNaoConformidadeEstanqueidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('causa', models.ManyToManyField(blank=True, related_name='causas_nao_conformidade_estanqueidade', to='inspecao.causas')),
                ('info_tubos_cilindros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.infoadicionaisexectuboscilindros')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoCausaEstanqueidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='causas_nao_conformidade_estanqueidade/')),
                ('causa_nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_estanqueidade', to='inspecao.causasnaoconformidadeestanqueidade')),
            ],
        ),
        migrations.DeleteModel(
            name='CausasEstanqueidadeTubosCilindros',
        ),
    ]
