# Generated by Django 5.0.6 on 2025-03-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0021_causasnaoconformidadeestanqueidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivocausaestanqueidade',
            old_name='arquivo',
            new_name='arquivos',
        ),
    ]
