# Generated by Django 5.0.6 on 2025-03-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0022_rename_arquivo_arquivocausaestanqueidade_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosexecucaoinspecaoestanqueidade',
            name='data_exec',
            field=models.DateTimeField(),
        ),
    ]
