# Generated by Django 5.0.6 on 2025-03-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0023_alter_dadosexecucaoinspecaoestanqueidade_data_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhespressaotanque',
            name='tipo_teste',
            field=models.CharField(choices=[('ctpi', 'Corpo do tanque parte inferior'), ('ctl', 'Corpo do tanque + longarinas'), ('ct', 'Corpo do tanque'), ('ctc', 'Corpo do tanque + chassi')], max_length=5),
        ),
    ]
