# Generated by Django 5.0.6 on 2025-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0024_alter_detalhespressaotanque_tipo_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspecao',
            name='reinspecionado',
            field=models.BooleanField(),
        ),
    ]
