# Generated by Django 4.2.15 on 2025-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0026_alter_reinspecao_reinspecionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosexecucaoinspecao',
            name='data_execucao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
