# Generated by Django 5.0.6 on 2025-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0027_alter_dadosexecucaoinspecao_data_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicionaisexectuboscilindros',
            name='ficha',
            field=models.ImageField(blank=True, null=True, upload_to='ficha_estamparia/'),
        ),
    ]
