# Generated by Django 5.0.6 on 2025-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0028_alter_infoadicionaisexectuboscilindros_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicionaisexectuboscilindros',
            name='ficha',
            field=models.ImageField(blank=True, null=True, upload_to='ficha_tubos_cilindros/'),
        ),
    ]
