# Generated by Django 5.2.4 on 2025-07-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_serra', '0007_infoadicionaisserrausinagem_medidasprocesso'),
        ('apontamento_usinagem', '0007_remove_pecasordem_definitiva_pecasordem_data'),
        ('inspecao', '0029_alter_infoadicionaisexectuboscilindros_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='pecas_ordem_serra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento_serra.pecasordem'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='pecas_ordem_usinagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento_usinagem.pecasordem'),
        ),
        migrations.AlterField(
            model_name='causas',
            name='setor',
            field=models.CharField(choices=[('pintura', 'Pintura'), ('montagem', 'Montagem'), ('estamparia', 'Estamparia'), ('serra-usinagem', 'Serra e Usinagem'), ('tubos cilindros', 'Tubos e Cilindros'), ('tanque', 'Tanque')], max_length=40),
        ),
    ]
