# Generated by Django 5.2.4 on 2025-08-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0030_inspecao_pecas_ordem_serra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='causasnaoconformidade',
            name='destino',
            field=models.CharField(blank=True, choices=[('retrabalho', 'Retrabalho'), ('sucata', 'Sucata')], default=None, max_length=10, null=True),
        ),
    ]
