# Generated by Django 5.2.4 on 2025-08-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0030_causas_excluida'),
        ('inspecao', '0031_causasnaoconformidade_destino'),
    ]

    operations = [
    ]
