# Generated by Django 5.2.4 on 2025-08-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0032_merge_20250812_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecaoestanqueidade'),
        ),
    ]
