# Generated by Django 5.2.4 on 2025-08-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0033_inspecao_tanque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecao',
            old_name='tanque',
            new_name='estanqueidade',
        ),
    ]
