# Generated by Django 5.2.4 on 2025-09-02 13:57

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0034_rename_tanque_inspecao_estanqueidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocausa',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='causas_nao_conformidade/'),
        ),
        migrations.AlterField(
            model_name='arquivocausaestanqueidade',
            name='arquivos',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='causas_nao_conformidade_estanqueidade/'),
        ),
        migrations.AlterField(
            model_name='infoadicionaisexectuboscilindros',
            name='ficha',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ficha_tubos_cilindros/'),
        ),
    ]
