# Generated by Django 5.2.4 on 2025-09-09 19:39

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0035_alter_arquivocausa_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='conformidades_reinspecao/')),
                ('dados_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_conformidade', to='inspecao.dadosexecucaoinspecao')),
            ],
        ),
    ]
