# Generated by Django 4.2.16 on 2025-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0036_arquivoconformidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosexecucaoinspecao',
            name='data_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
