# Generated by Django 4.2.16 on 2025-10-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0037_alter_dadosexecucaoinspecao_data_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosexecucaoinspecao',
            name='data_execucao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
