# Generated by Codex on 2025-12-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apontamento_corte", "0006_alter_pecasordem_unique_together"),
        ("inspecao", "0038_alter_dadosexecucaoinspecao_data_execucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecao",
            name="pecas_ordem_corte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apontamento_corte.pecasordem",
            ),
        ),
    ]
