# Generated by Django 4.2.16 on 2025-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0039_inspecao_pecas_ordem_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causas',
            name='setor',
            field=models.CharField(choices=[('pintura', 'Pintura'), ('montagem', 'Montagem'), ('estamparia', 'Estamparia'), ('serra-usinagem', 'Serra e Usinagem'), ('tubos cilindros', 'Tubos e Cilindros'), ('corte', 'Corte'), ('tanque', 'Tanque')], max_length=40),
        ),
    ]
