# Generated by Django 4.2.16 on 2026-02-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_consultasaldoinnovaro_core_consul_codigo_f3813a_idx_and_more'),
        ('inspecao', '0040_alter_causas_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateTimeField(auto_now_add=True)),
                ('planilha_id', models.CharField(max_length=120)),
                ('aba_nome', models.CharField(max_length=120)),
                ('linha_planilha', models.IntegerField(blank=True, null=True)),
                ('sheet_hash', models.CharField(max_length=64, unique=True)),
                ('dados', models.JSONField()),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Nao conforme')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('inspetor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
    ]
