# Generated by Django 4.2.16 on 2026-02-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_consultasaldoinnovaro_core_consul_codigo_f3813a_idx_and_more'),
        ('inspecao', '0041_inspecao_recebimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoRecebimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('planilha_id', models.CharField(max_length=120)),
                ('aba_nome', models.CharField(max_length=120)),
                ('linha_planilha', models.IntegerField(blank=True, null=True)),
                ('sheet_hash', models.CharField(max_length=64, unique=True)),
                ('dados', models.JSONField()),
                ('data_referencia', models.DateField()),
                ('status_h', models.BooleanField(default=False)),
                ('inspecionado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inspecaorecebimento',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes', to='inspecao.inspecaorecebimentoitem'),
        ),
    ]
