# Generated by Django 4.2.16 on 2026-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0042_inspecao_recebimento_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecaorecebimento',
            name='dados_inspecao',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
