# Generated by Django 4.2.16 on 2026-03-26 18:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_consultasaldoinnovaro_core_consul_codigo_f3813a_idx_and_more'),
        ('inspecao', '0043_inspecaorecebimento_dados_inspecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseBanhoEzinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('desengraxante_amostra_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('desengraxante_amostra_2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('desengraxante_amostra_3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('desengraxante_media', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ak_l95_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fosfatizante_amostra_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fosfatizante_amostra_2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fosfatizante_amostra_3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fosfatizante_media', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('m_fe_212_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ak_l95_adicionar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('aditivo_adicionar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('m_fe_212_adicionar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
            options={
                'verbose_name': 'Análise de Banho EZINGER',
                'verbose_name_plural': 'Análises de Banho EZINGER',
                'ordering': ('-registrado_em',),
            },
        ),
    ]
