# Generated by Django 4.2.16 on 2026-03-26 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0044_analisebanhoezinger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisebanhoezinger',
            name='registrado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
