# Generated by Django 4.2.16 on 2026-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0045_alter_analisebanhoezinger_registrado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisebanhoezinger',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
