# Generated by Django 4.2.15 on 2024-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_usinagem', '0003_rename_quantidade_pecasordem_qtd_boa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasordem',
            name='qtd_boa',
            field=models.FloatField(default=0),
        ),
    ]
