# Generated by Django 4.2.15 on 2025-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_usinagem', '0004_alter_pecasordem_qtd_boa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='definitiva',
            field=models.BooleanField(default=False),
        ),
    ]
