# Generated by Django 4.2.15 on 2025-01-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_processo'),
        ('apontamento_usinagem', '0005_pecasordem_definitiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasordem',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_produzido', to='cadastro.operador'),
        ),
    ]
