# Generated by Django 4.2.15 on 2025-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento_usinagem', '0006_pecasordem_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasordem',
            name='definitiva',
        ),
        migrations.AddField(
            model_name='pecasordem',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
